# General Labels
GitHub:
  - .github/**/*

Notebooks:
  - notebooks/**/*

# Package Labels
plot:
  - cosmic_conchometer/plot/**/*

scripts:
  - cosmic_conchometer/scripts/**/*

utils:
  - cosmic_conchometer/utils/**/*


# Docs Labels
Docs:
  - docs/**/*

docs.utils:
  - docs/cosmic_conchometer/utils/**/*
